
  create table "public"."activity" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" date not null,
    "workout_id" bigint not null
      );


alter table "public"."activity" enable row level security;


  create table "public"."project_images" (
    "id" bigint generated by default as identity not null,
    "project_id" bigint not null,
    "image_url" text not null
      );


alter table "public"."project_images" enable row level security;


  create table "public"."project_skills" (
    "project_id" bigint not null,
    "skills_id" bigint not null
      );


alter table "public"."project_skills" enable row level security;


  create table "public"."project_team_members" (
    "project_id" bigint generated by default as identity not null,
    "team_member_id" bigint generated by default as identity not null
      );


alter table "public"."project_team_members" enable row level security;


  create table "public"."projects" (
    "id" bigint generated by default as identity not null,
    "start_date" date not null,
    "description" text not null,
    "link" text not null,
    "name" text not null
      );


alter table "public"."projects" enable row level security;


  create table "public"."skills" (
    "id" bigint generated by default as identity not null,
    "level" text not null,
    "type" text not null,
    "sub_type" text,
    "name" text not null,
    "color" text
      );


alter table "public"."skills" enable row level security;


  create table "public"."team_members" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "image_url" text not null,
    "github_link" text not null
      );


alter table "public"."team_members" enable row level security;


  create table "public"."testimonials" (
    "slug" text not null,
    "received_at" date not null,
    "content" text not null,
    "name" text not null,
    "image_url" text not null,
    "email" text not null,
    "company" text not null,
    "company_logo_url" text not null,
    "description" text not null,
    "quote" text not null
      );


alter table "public"."testimonials" enable row level security;


  create table "public"."workout" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "url" text not null,
    "duration" smallint not null,
    "title" text not null,
    "type" text,
    "intensity" smallint not null,
    "videoId" text not null
      );


alter table "public"."workout" enable row level security;


  create table "public"."workout_activity" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" date not null,
    "workout_id" bigint not null,
    "completed" boolean not null default false
      );


alter table "public"."workout_activity" enable row level security;

CREATE UNIQUE INDEX project_images_pkey ON public.project_images USING btree (id);

CREATE UNIQUE INDEX project_skills_pkey ON public.project_skills USING btree (project_id, skills_id);

CREATE UNIQUE INDEX project_team_members_pkey ON public.project_team_members USING btree (team_member_id, project_id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

CREATE UNIQUE INDEX skills_name_key ON public.skills USING btree (name);

CREATE UNIQUE INDEX skills_pkey ON public.skills USING btree (id);

CREATE UNIQUE INDEX team_members_pkey ON public.team_members USING btree (id);

CREATE UNIQUE INDEX testimonials_pkey ON public.testimonials USING btree (slug);

CREATE UNIQUE INDEX workout_activity_pkey ON public.workout_activity USING btree (id);

CREATE UNIQUE INDEX workout_pkey ON public.workout USING btree (id);

CREATE UNIQUE INDEX workout_url_key ON public.workout USING btree (url);

alter table "public"."project_images" add constraint "project_images_pkey" PRIMARY KEY using index "project_images_pkey";

alter table "public"."project_skills" add constraint "project_skills_pkey" PRIMARY KEY using index "project_skills_pkey";

alter table "public"."project_team_members" add constraint "project_team_members_pkey" PRIMARY KEY using index "project_team_members_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."skills" add constraint "skills_pkey" PRIMARY KEY using index "skills_pkey";

alter table "public"."team_members" add constraint "team_members_pkey" PRIMARY KEY using index "team_members_pkey";

alter table "public"."testimonials" add constraint "testimonials_pkey" PRIMARY KEY using index "testimonials_pkey";

alter table "public"."workout" add constraint "workout_pkey" PRIMARY KEY using index "workout_pkey";

alter table "public"."workout_activity" add constraint "workout_activity_pkey" PRIMARY KEY using index "workout_activity_pkey";

alter table "public"."project_images" add constraint "project_images_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE not valid;

alter table "public"."project_images" validate constraint "project_images_project_id_fkey";

alter table "public"."project_skills" add constraint "project_skills_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE not valid;

alter table "public"."project_skills" validate constraint "project_skills_project_id_fkey";

alter table "public"."project_skills" add constraint "project_skills_skills_id_fkey" FOREIGN KEY (skills_id) REFERENCES public.skills(id) ON DELETE CASCADE not valid;

alter table "public"."project_skills" validate constraint "project_skills_skills_id_fkey";

alter table "public"."project_team_members" add constraint "project_team_members_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE not valid;

alter table "public"."project_team_members" validate constraint "project_team_members_project_id_fkey";

alter table "public"."project_team_members" add constraint "project_team_members_team_member_id_fkey" FOREIGN KEY (team_member_id) REFERENCES public.team_members(id) ON DELETE CASCADE not valid;

alter table "public"."project_team_members" validate constraint "project_team_members_team_member_id_fkey";

alter table "public"."workout" add constraint "workout_url_key" UNIQUE using index "workout_url_key";

alter table "public"."workout_activity" add constraint "workout_activity_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES public.workout(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."workout_activity" validate constraint "workout_activity_workout_id_fkey";

grant delete on table "public"."activity" to "anon";

grant insert on table "public"."activity" to "anon";

grant references on table "public"."activity" to "anon";

grant select on table "public"."activity" to "anon";

grant trigger on table "public"."activity" to "anon";

grant truncate on table "public"."activity" to "anon";

grant update on table "public"."activity" to "anon";

grant delete on table "public"."activity" to "authenticated";

grant insert on table "public"."activity" to "authenticated";

grant references on table "public"."activity" to "authenticated";

grant select on table "public"."activity" to "authenticated";

grant trigger on table "public"."activity" to "authenticated";

grant truncate on table "public"."activity" to "authenticated";

grant update on table "public"."activity" to "authenticated";

grant delete on table "public"."activity" to "postgres";

grant insert on table "public"."activity" to "postgres";

grant references on table "public"."activity" to "postgres";

grant select on table "public"."activity" to "postgres";

grant trigger on table "public"."activity" to "postgres";

grant truncate on table "public"."activity" to "postgres";

grant update on table "public"."activity" to "postgres";

grant delete on table "public"."activity" to "service_role";

grant insert on table "public"."activity" to "service_role";

grant references on table "public"."activity" to "service_role";

grant select on table "public"."activity" to "service_role";

grant trigger on table "public"."activity" to "service_role";

grant truncate on table "public"."activity" to "service_role";

grant update on table "public"."activity" to "service_role";

grant delete on table "public"."project_images" to "anon";

grant insert on table "public"."project_images" to "anon";

grant references on table "public"."project_images" to "anon";

grant select on table "public"."project_images" to "anon";

grant trigger on table "public"."project_images" to "anon";

grant truncate on table "public"."project_images" to "anon";

grant update on table "public"."project_images" to "anon";

grant delete on table "public"."project_images" to "authenticated";

grant insert on table "public"."project_images" to "authenticated";

grant references on table "public"."project_images" to "authenticated";

grant select on table "public"."project_images" to "authenticated";

grant trigger on table "public"."project_images" to "authenticated";

grant truncate on table "public"."project_images" to "authenticated";

grant update on table "public"."project_images" to "authenticated";

grant delete on table "public"."project_images" to "service_role";

grant insert on table "public"."project_images" to "service_role";

grant references on table "public"."project_images" to "service_role";

grant select on table "public"."project_images" to "service_role";

grant trigger on table "public"."project_images" to "service_role";

grant truncate on table "public"."project_images" to "service_role";

grant update on table "public"."project_images" to "service_role";

grant delete on table "public"."project_skills" to "anon";

grant insert on table "public"."project_skills" to "anon";

grant references on table "public"."project_skills" to "anon";

grant select on table "public"."project_skills" to "anon";

grant trigger on table "public"."project_skills" to "anon";

grant truncate on table "public"."project_skills" to "anon";

grant update on table "public"."project_skills" to "anon";

grant delete on table "public"."project_skills" to "authenticated";

grant insert on table "public"."project_skills" to "authenticated";

grant references on table "public"."project_skills" to "authenticated";

grant select on table "public"."project_skills" to "authenticated";

grant trigger on table "public"."project_skills" to "authenticated";

grant truncate on table "public"."project_skills" to "authenticated";

grant update on table "public"."project_skills" to "authenticated";

grant delete on table "public"."project_skills" to "service_role";

grant insert on table "public"."project_skills" to "service_role";

grant references on table "public"."project_skills" to "service_role";

grant select on table "public"."project_skills" to "service_role";

grant trigger on table "public"."project_skills" to "service_role";

grant truncate on table "public"."project_skills" to "service_role";

grant update on table "public"."project_skills" to "service_role";

grant delete on table "public"."project_team_members" to "anon";

grant insert on table "public"."project_team_members" to "anon";

grant references on table "public"."project_team_members" to "anon";

grant select on table "public"."project_team_members" to "anon";

grant trigger on table "public"."project_team_members" to "anon";

grant truncate on table "public"."project_team_members" to "anon";

grant update on table "public"."project_team_members" to "anon";

grant delete on table "public"."project_team_members" to "authenticated";

grant insert on table "public"."project_team_members" to "authenticated";

grant references on table "public"."project_team_members" to "authenticated";

grant select on table "public"."project_team_members" to "authenticated";

grant trigger on table "public"."project_team_members" to "authenticated";

grant truncate on table "public"."project_team_members" to "authenticated";

grant update on table "public"."project_team_members" to "authenticated";

grant delete on table "public"."project_team_members" to "service_role";

grant insert on table "public"."project_team_members" to "service_role";

grant references on table "public"."project_team_members" to "service_role";

grant select on table "public"."project_team_members" to "service_role";

grant trigger on table "public"."project_team_members" to "service_role";

grant truncate on table "public"."project_team_members" to "service_role";

grant update on table "public"."project_team_members" to "service_role";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";

grant delete on table "public"."skills" to "anon";

grant insert on table "public"."skills" to "anon";

grant references on table "public"."skills" to "anon";

grant select on table "public"."skills" to "anon";

grant trigger on table "public"."skills" to "anon";

grant truncate on table "public"."skills" to "anon";

grant update on table "public"."skills" to "anon";

grant delete on table "public"."skills" to "authenticated";

grant insert on table "public"."skills" to "authenticated";

grant references on table "public"."skills" to "authenticated";

grant select on table "public"."skills" to "authenticated";

grant trigger on table "public"."skills" to "authenticated";

grant truncate on table "public"."skills" to "authenticated";

grant update on table "public"."skills" to "authenticated";

grant delete on table "public"."skills" to "service_role";

grant insert on table "public"."skills" to "service_role";

grant references on table "public"."skills" to "service_role";

grant select on table "public"."skills" to "service_role";

grant trigger on table "public"."skills" to "service_role";

grant truncate on table "public"."skills" to "service_role";

grant update on table "public"."skills" to "service_role";

grant delete on table "public"."team_members" to "anon";

grant insert on table "public"."team_members" to "anon";

grant references on table "public"."team_members" to "anon";

grant select on table "public"."team_members" to "anon";

grant trigger on table "public"."team_members" to "anon";

grant truncate on table "public"."team_members" to "anon";

grant update on table "public"."team_members" to "anon";

grant delete on table "public"."team_members" to "authenticated";

grant insert on table "public"."team_members" to "authenticated";

grant references on table "public"."team_members" to "authenticated";

grant select on table "public"."team_members" to "authenticated";

grant trigger on table "public"."team_members" to "authenticated";

grant truncate on table "public"."team_members" to "authenticated";

grant update on table "public"."team_members" to "authenticated";

grant delete on table "public"."team_members" to "service_role";

grant insert on table "public"."team_members" to "service_role";

grant references on table "public"."team_members" to "service_role";

grant select on table "public"."team_members" to "service_role";

grant trigger on table "public"."team_members" to "service_role";

grant truncate on table "public"."team_members" to "service_role";

grant update on table "public"."team_members" to "service_role";

grant delete on table "public"."testimonials" to "anon";

grant insert on table "public"."testimonials" to "anon";

grant references on table "public"."testimonials" to "anon";

grant select on table "public"."testimonials" to "anon";

grant trigger on table "public"."testimonials" to "anon";

grant truncate on table "public"."testimonials" to "anon";

grant update on table "public"."testimonials" to "anon";

grant delete on table "public"."testimonials" to "authenticated";

grant insert on table "public"."testimonials" to "authenticated";

grant references on table "public"."testimonials" to "authenticated";

grant select on table "public"."testimonials" to "authenticated";

grant trigger on table "public"."testimonials" to "authenticated";

grant truncate on table "public"."testimonials" to "authenticated";

grant update on table "public"."testimonials" to "authenticated";

grant delete on table "public"."testimonials" to "service_role";

grant insert on table "public"."testimonials" to "service_role";

grant references on table "public"."testimonials" to "service_role";

grant select on table "public"."testimonials" to "service_role";

grant trigger on table "public"."testimonials" to "service_role";

grant truncate on table "public"."testimonials" to "service_role";

grant update on table "public"."testimonials" to "service_role";

grant delete on table "public"."workout" to "anon";

grant insert on table "public"."workout" to "anon";

grant references on table "public"."workout" to "anon";

grant select on table "public"."workout" to "anon";

grant trigger on table "public"."workout" to "anon";

grant truncate on table "public"."workout" to "anon";

grant update on table "public"."workout" to "anon";

grant delete on table "public"."workout" to "authenticated";

grant insert on table "public"."workout" to "authenticated";

grant references on table "public"."workout" to "authenticated";

grant select on table "public"."workout" to "authenticated";

grant trigger on table "public"."workout" to "authenticated";

grant truncate on table "public"."workout" to "authenticated";

grant update on table "public"."workout" to "authenticated";

grant delete on table "public"."workout" to "postgres";

grant insert on table "public"."workout" to "postgres";

grant references on table "public"."workout" to "postgres";

grant select on table "public"."workout" to "postgres";

grant trigger on table "public"."workout" to "postgres";

grant truncate on table "public"."workout" to "postgres";

grant update on table "public"."workout" to "postgres";

grant delete on table "public"."workout" to "service_role";

grant insert on table "public"."workout" to "service_role";

grant references on table "public"."workout" to "service_role";

grant select on table "public"."workout" to "service_role";

grant trigger on table "public"."workout" to "service_role";

grant truncate on table "public"."workout" to "service_role";

grant update on table "public"."workout" to "service_role";

grant delete on table "public"."workout_activity" to "anon";

grant insert on table "public"."workout_activity" to "anon";

grant references on table "public"."workout_activity" to "anon";

grant select on table "public"."workout_activity" to "anon";

grant trigger on table "public"."workout_activity" to "anon";

grant truncate on table "public"."workout_activity" to "anon";

grant update on table "public"."workout_activity" to "anon";

grant delete on table "public"."workout_activity" to "authenticated";

grant insert on table "public"."workout_activity" to "authenticated";

grant references on table "public"."workout_activity" to "authenticated";

grant select on table "public"."workout_activity" to "authenticated";

grant trigger on table "public"."workout_activity" to "authenticated";

grant truncate on table "public"."workout_activity" to "authenticated";

grant update on table "public"."workout_activity" to "authenticated";

grant delete on table "public"."workout_activity" to "postgres";

grant insert on table "public"."workout_activity" to "postgres";

grant references on table "public"."workout_activity" to "postgres";

grant select on table "public"."workout_activity" to "postgres";

grant trigger on table "public"."workout_activity" to "postgres";

grant truncate on table "public"."workout_activity" to "postgres";

grant update on table "public"."workout_activity" to "postgres";

grant delete on table "public"."workout_activity" to "service_role";

grant insert on table "public"."workout_activity" to "service_role";

grant references on table "public"."workout_activity" to "service_role";

grant select on table "public"."workout_activity" to "service_role";

grant trigger on table "public"."workout_activity" to "service_role";

grant truncate on table "public"."workout_activity" to "service_role";

grant update on table "public"."workout_activity" to "service_role";


  create policy "Enable read access for all users"
  on "public"."project_images"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."project_skills"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."project_team_members"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."projects"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."skills"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."team_members"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."testimonials"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for all users"
  on "public"."workout"
  as permissive
  for insert
  to anon
with check (true);



  create policy "Enable read access for all users"
  on "public"."workout"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for anon users"
  on "public"."workout_activity"
  as permissive
  for insert
  to anon
with check (true);



  create policy "Enable read access for all users"
  on "public"."workout_activity"
  as permissive
  for select
  to public
using (true);



