drop extension if exists "pg_net";

create extension if not exists "http" with schema "public";

create extension if not exists "pg_cron" with schema "public";

drop policy "Enable insert for all users" on "public"."workout";

revoke delete on table "public"."activity" from "anon";

revoke insert on table "public"."activity" from "anon";

revoke references on table "public"."activity" from "anon";

revoke select on table "public"."activity" from "anon";

revoke trigger on table "public"."activity" from "anon";

revoke truncate on table "public"."activity" from "anon";

revoke update on table "public"."activity" from "anon";

revoke delete on table "public"."activity" from "authenticated";

revoke insert on table "public"."activity" from "authenticated";

revoke references on table "public"."activity" from "authenticated";

revoke select on table "public"."activity" from "authenticated";

revoke trigger on table "public"."activity" from "authenticated";

revoke truncate on table "public"."activity" from "authenticated";

revoke update on table "public"."activity" from "authenticated";

revoke delete on table "public"."activity" from "service_role";

revoke insert on table "public"."activity" from "service_role";

revoke references on table "public"."activity" from "service_role";

revoke select on table "public"."activity" from "service_role";

revoke trigger on table "public"."activity" from "service_role";

revoke truncate on table "public"."activity" from "service_role";

revoke update on table "public"."activity" from "service_role";

drop table "public"."activity";


  create table "public"."subscriptions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "endpoint" text not null,
    "expiration_time" numeric,
    "p256dh" text not null,
    "auth" text not null
      );


alter table "public"."subscriptions" enable row level security;

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."skills" add constraint "skills_name_key" UNIQUE using index "skills_name_key";

create type "public"."http_header" as ("field" character varying, "value" character varying);

create type "public"."http_request" as ("method" public.http_method, "uri" character varying, "headers" public.http_header[], "content_type" character varying, "content" character varying);

create type "public"."http_response" as ("status" integer, "content_type" character varying, "headers" public.http_header[], "content" character varying);

grant delete on table "public"."subscriptions" to "anon";

grant insert on table "public"."subscriptions" to "anon";

grant references on table "public"."subscriptions" to "anon";

grant select on table "public"."subscriptions" to "anon";

grant trigger on table "public"."subscriptions" to "anon";

grant truncate on table "public"."subscriptions" to "anon";

grant update on table "public"."subscriptions" to "anon";

grant delete on table "public"."subscriptions" to "authenticated";

grant insert on table "public"."subscriptions" to "authenticated";

grant references on table "public"."subscriptions" to "authenticated";

grant select on table "public"."subscriptions" to "authenticated";

grant trigger on table "public"."subscriptions" to "authenticated";

grant truncate on table "public"."subscriptions" to "authenticated";

grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";

grant insert on table "public"."subscriptions" to "service_role";

grant references on table "public"."subscriptions" to "service_role";

grant select on table "public"."subscriptions" to "service_role";

grant trigger on table "public"."subscriptions" to "service_role";

grant truncate on table "public"."subscriptions" to "service_role";

grant update on table "public"."subscriptions" to "service_role";


  create policy "enable everything for everyone"
  on "public"."subscriptions"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "Enable insert for anon users"
  on "public"."workout"
  as permissive
  for insert
  to anon
with check (true);



  create policy "Enable update access for all users"
  on "public"."workout_activity"
  as permissive
  for update
  to public
using (true)
with check (true);



